# For more information: https://docs.art/reference/test-script#config-section
config:
  target: "https://www.google.com/"

  includeFiles:
    - page-objects
    - tests
    - utils
    - test-data

  environments:
    stage: 
      target: "https://www.google.com"
    prod:
      target: "https://yahoo.com"

  phases:
    - name: 'Warm-up Phase'
      duration: 1
      arrivalRate: 1
      rampTo: 1
      
  engines:
    playwright:
      trace: true
      launchOptions:
        headless: true

  plugins:
    ensure: {}
    expect: {}

  #ensure:
  #  min: 2500000
